### 로그인
POST http://localhost:3000/login/authenticate
Content-Type: application/json

{
    "username": "test_0",
    "password": "test"
}

### 게시글 조회
GET http://localhost:3000/board/1


### 게시글 목록
GET http://localhost:3000/board?pageNo=1&pageSize=2&sort=created_at,desc&sort=updated_at,desc
content-type: application/json

### 게시글 작성
POST http://localhost:3000/board
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjk5NjA0OTcwLCJleHAiOjE2OTk2MDY3NzAsImlzcyI6Im15LXNlcnZpY2UifQ.mgFj2kRKUxmWQPOCbl7R2e_uZImaw32rQUZPHRFrqFE

{
    "title":"글제목스",
    "content":"글내용스"
}

### 회원가입 day_11
POST http://localhost:3000/signup
Content-Type: application/json

{
    "email":"zero2080@naver.com",
    "password":"1234"
}

### 회원가입 day_11
POST http://localhost:3000/signup
Content-Type: application/json

{
    "email":"zero2080@naver.com",
    "password":"1234"
}

### 로그인 day_11
POST http://localhost:3000/login

{
    "username":"zero2080@naver.com",
    "password":"1234"
}