### 로그인
POST http://localhost:3000/login/authenticate
Content-Type: application/json

{
    "username": "test_0",
    "password": "test"
}

### 게시글 조회
GET http://localhost:3000/board/0


### 게시글 목록
GET http://localhost:3000/board?pageNo=51&pageSize=2&sort=createdAt,desc&updatedAt,desc
content-type: application/json

### 게시글 작성
POST http://localhost:3000/board
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwiaWF0IjoxNjk5MzUwNzQ5LCJleHAiOjE2OTkzNTI1NDksImlzcyI6Im15LXNlcnZpY2UifQ.zZqxq-bM54JS6Ey4O1aiyR5xTETCe89pU3nOLME0mvU

{
    "title":"글제목스",
    "content":"글내용스"
}

###
GET http://localhost:3000/login/coo